Added SteamID Support.
rogeraabbccdd/CSGO-MVP pull request #24
Opened 2021-09-02 10:26 UTC by kratos1812

Now you can limit the acces to a Custom MVP to a single steamid. Example in kento_mvp.cfg. I've seen many people requesting this.

2021-09-02 13:45 UTC, rogeraabbccdd commented
Looks like this PR only support 1 SteamID.
I think multiple SteamID support would be better.

2021-09-02 22:53 UTC, kratos1812 commented
> Looks like this PR only support 1 SteamID.
> I think multiple SteamID support would be better.

Just pushed a new commit. I tested it and works well(debuged it, etc etc).
I've added a new cvar too `mvp_no_acces_show_mode`.

2021-09-04 03:12 UTC, rogeraabbccdd requested changes

2021-09-04 03:12 UTC, rogeraabbccdd commented on addons/sourcemod/scripting/kento_mvp.sp
> +					switch(Cvar_ShowMode.IntValue)
I think hook cvar change and store value in a variable is better than calling `.IntValue` everytime.

2021-09-05 06:40 UTC, rogeraabbccdd commented
LGTM

2021-09-05 06:40 UTC, merged